authe/urls.py
from django.urls import path
from authe.views import *
app_name = 'authe'

urlpatterns = [
    path(route='register/', view=register_view, name="register"),
    path(route='register_admin/', view=register_admin_view,
         name="register_admin"),
    path(route='login/', view=login_view, name="login"),
    path(route='otp/', view=otp_view, name="otp"),
    path(route='home/', view=home_view, name="home"),
    path(route='admin_home/', view=admin_home_view, name="admin_home"),
    path(route='logout/', view=logout_view, name="logout"),
]

food/urls.py
from django.urls import path
from food.views import *
app_name = "food"
urlpatterns = [
    path(route='album/', view=album_view, name="album"),
    path(route='item_create/', view=create_item_view, name="items_create"),
    path(route='item_update/<int:pk>/',
         view=update_item_view, name="item_update"),
    path(route='item_delete/<int:pk>/',
         view=delete_item_view, name="item_delete"),

    path(route='food_create/', view=create_food_view, name="food_create"),
    path(route='food_list/', view=list_food_view, name="food_list"),
    path(route='food_update/<int:pk>/',
         view=update_food_view, name="food_update"),
    path(route='food_delete/<int:pk>/',
         view=delete_food_view, name="food_delete"),

    path(route='cart_add/<int:cust>/<int:food>/',
         view=cart_add, name="cart_add"),
    path(route='cart_list/',
         view=cart_list, name="cart_list"),
    path(route='remove_food/<int:pk>/',
         view=remove_food, name="remove_food"),

    path(route='checkout_food/',
         view=checkout_food, name="checkout_food"),


]

pro10/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from pro10.views import index_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path(route='authe/', view=include('authe.urls')),
    path(route='', view=index_view, name="index"),
    path(route='food/', view=include('food.urls'), name="food"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models

# Create your models here.


class menu_items(models.Model):
    mid = models.SmallAutoField(primary_key=True)
    i_name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.i_name


class food_items(models.Model):
    fid = models.BigAutoField(primary_key=True)
    mid = models.ForeignKey(menu_items, on_delete=models.CASCADE)
    f_name = models.CharField(max_length=50)
    f_desc = models.TextField()
    f_quantity = models.PositiveIntegerField(default=1)
    f_price = models.PositiveIntegerField(default=30)
    discount = models.PositiveSmallIntegerField(default=0)
    f_img = models.ImageField()


class cart_items(models.Model):
    cart_id = models.AutoField(primary_key=True)
    cust_id = models.IntegerField()
    food_id = models.IntegerField()


class order_food(models.Model):
    oid = models.AutoField(primary_key=True)
    cust_id = models.PositiveIntegerField()
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.PositiveBigIntegerField()
    address = models.TextField()
    shipping_address = models.BooleanField()
    country = models.CharField(max_length=30, choices=[
                               ['India', 'India'], ['USA', 'USA'], ['UK', 'UK']])
    states = models.CharField(max_length=30, choices=[['AP', 'AP'], [
                              'TS', 'TS'], ['SR', 'SR'], ['TN', 'TN']])
    pincode = models.PositiveIntegerField()
    order_date = models.DateTimeField(auto_now=True)
    total_price = models.FloatField()
    


class order_food_items(models.Model):
    oid = models.ForeignKey(order_food, on_delete=models.CASCADE)
    food_id = models.PositiveIntegerField()
    price = models.FloatField()
    quantity = models.PositiveIntegerField()

food/forms.py
from django import forms
from food.models import menu_items, food_items, order_food


class menu_items_form(forms.ModelForm):
    class Meta:
        model = menu_items
        fields = '__all__'


class food_items_form(forms.ModelForm):
    class Meta:
        model = food_items
        fields = '__all__'


class order_food_items_form(forms.ModelForm):
    class Meta:
        model = order_food
        exclude = ['cust_id', 'total_price']

food/views.py
from django.shortcuts import render, redirect
from food.forms import menu_items_form, food_items_form, order_food_items_form
from food.models import menu_items, food_items, cart_items
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Sum, Count
# Create your views here.


@login_required(login_url='/authe/login')
def album_view(request):
    res = food_items.objects.all()
    return render(request=request, template_name='album.html', context={'res': res})


@login_required(login_url='/authe/login')
def create_item_view(request):
    res = menu_items.objects.all()
    form = menu_items_form()
    if request.method == 'POST':
        print(request.POST)
        form = menu_items_form(request.POST)
        if form.is_valid:
            form.save()
    if request.method == 'GET':
        res = menu_items.objects.all()
    return render(request=request, template_name='items_create.html', context={'form': form, 'res': res})


@login_required(login_url='/authe/login')
def update_item_view(request, pk):
    res = menu_items.objects.get(mid=pk)
    form = menu_items_form(instance=res)
    if request.method == 'POST':
        res = menu_items.objects.get(mid=pk)
        form = menu_items_form(request.POST, instance=res)
        if form.is_valid:
            form.save()
            return redirect('/food/item_create')
    return render(request=request, template_name='item_update.html', context={'form': form})


@login_required(login_url='/authe/login')
def delete_item_view(request, pk):
    res = menu_items.objects.get(mid=pk)
    if request.method == 'POST':
        res = menu_items.objects.get(mid=pk).delete()
        return redirect('/food/item_create')
    return render(request=request, template_name='item_delete.html', context={'res': res})


@login_required(login_url='/authe/login')
def create_food_view(request):
    form = food_items_form()
    if request.method == 'POST':
        print(request.POST, request.FILES)
        form = food_items_form(request.POST, request.FILES)
        if form.is_valid:
            form.save()
            return redirect('/food/food_list')
    return render(request=request, template_name='food_create.html', context={'form': form})


@login_required(login_url='/authe/login')
def list_food_view(request):
    res = food_items.objects.all()
    return render(request=request, template_name='food_list.html', context={'res': res})


@login_required(login_url='/authe/login')
def update_food_view(request, pk):
    res = food_items.objects.get(fid=pk)
    form = food_items_form(instance=res)
    if request.method == 'POST':
        res = food_items.objects.get(fid=pk)
        form = food_items_form(request.POST, request.FILES, instance=res)
        if form.is_valid:
            form.save()
            return redirect('/food/food_list')
    return render(request=request, template_name='food_update.html', context={'form': form})


@login_required(login_url='/authe/login')
def delete_food_view(request, pk):
    res = food_items.objects.get(fid=pk)
    if request.method == 'POST':
        res = food_items.objects.get(fid=pk).delete()
        return redirect('/food/food_list')
    return render(request=request, template_name='food_delete.html', context={'res': res})


@login_required(login_url='/authe/login')
def cart_add(request, cust, food):
    cart_items.objects.create(cust_id=cust, food_id=food)
    messages.success(request, "Item is added")
    return redirect('/food/album')


@login_required(login_url='/authe/login')
def cart_list(request):
    res = cart_items.objects.filter(cust_id=request.user.id)
    food_data = [j[0] for j in res.values_list('food_id', 'cart_id')]
    cart_data = [j[1] for j in res.values_list('food_id', 'cart_id')]
    data = food_items.objects.filter(fid__in=food_data)
    data = [(data[i], cart_data[i]) for i in range(0, len(data))]
    return render(request=request, template_name='cart_list.html', context={'data': data})


@login_required(login_url='/authe/login')
def remove_food(request, pk):
    cart_items.objects.get(cart_id=pk).delete()
    messages.success(request, "food item removed")
    return redirect('/food/cart_list')


@login_required(login_url='/authe/login')
def checkout_food(request):
    res = cart_items.objects.filter(
        cust_id=request.user.id).values_list('food_id')
    print()
    food_data = [food_items.objects.get(fid=i) for i in [i[0] for i in res]]
    print(food_data)
    food_count = [food_items.objects.get(fid=i).f_price for i in [
        i[0] for i in res]]
    print(food_count)
    form = order_food_items_form()
    total_price = sum(food_count)
    data = {'form': form, 'food_data': food_data,
            'f_price__sum': total_price, 'f_price__count': len(food_count)}
    if request.method == 'POST':
        print(request.POST)
        form = order_food_items_form(request.POST)
        if form.is_valid:
            user = form.save(commit=False)
            user.cust_id = request.user.id
            user.total_price = total_price
            if True:
                user.save()
                messages.success(request, "booking success")
                return redirect('/food/album')
    return render(request=request, template_name='checkout.html', context=data)

food/templates/cart_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% block message1 %}
    {% if messages %}
    {% for msg in messages %}
    <div class="alert alert-warning" role="alert">
        {{msg}}
    </div>
    {% endfor %}
    {% endif %}

    {% endblock %}



    {%if data %}
    <table border="2">
        <tr>
            <th>
                Name
            </th>
            <th>
                Quantity
            </th>
            <th>
                Price
            </th>
            <th>
                Remove_item
            </th>
        </tr>
        {% for i in data %}
        <tr>
            <td>
                {{i.0.f_name}}
            </td>
            <td>
                {{i.0.f_quantity}}
            </td>
            <td>
                {{i.0.f_price}}
            </td>
            <td>
                <a href="{% url 'food:remove_food' pk=i.1 %}"> <button>Remove</button></a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <a href="{%url 'food:checkout_food'%}"><button class="bn btn-primary">Items Book</button></a>
    {% else %}
    <h1>cart is empty</h1>
    {% endif %}

</body>

</html>

food/templates/food_delete.html
{% extends 'items_create.html'%}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <h2>Are You Sure To Delete</h2>
    <h3>Food No: {{res.fid}} </h3>
    <h3>Food Name: {{res.f_name}}</h3>
    <button class="btn btn-primary w-45 py-2" type="submit">Delete</button>
    <a href="{%url 'food:food_create' %}" class="btn btn-success w-45 py-2" type="submit">Create Food</a>
</form>
{% endblock %}

food/templates/food_list.html
<!doctype html>
<html lang="en" data-bs-theme="auto">

<head>
    {% load static %}

    <script src="{% static 'js/color-modes.js' %}"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>Food Items</title>

    {% include 'partials/_bootcss.html' %}

    <style>
        .bd-placeholder-img {
            font-size: medium;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
            z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
            display: block !important;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/sign-in.css'%}" rel="stylesheet">
</head>

<body class="d-flex align-items-center py-4 bg-body-tertiary">
    <main class="w-10 m-auto">
        {% block content %}
        <div>
            <table border="2">
                <tr>
                    <th>
                        <h1>Food No</h1>
                    </th>
                    <th>
                        <h1>Name </h1>
                    </th>
                    <th>
                        <h1>Description </h1>
                    </th>

                    <th>
                        <h1>Quantity </h1>
                    </th>
                    <th>
                        <h1>Price </h1>
                    </th>
                    <th>
                        <h1>Discount </h1>
                    </th>
                    <th>
                        <h1>Images </h1>
                    </th>
                    <th>
                        <h1>Update</h1>
                    </th>
                    <th>
                        <h1>Delete</h1>
                    </th>
                </tr>
                {% for i in res %}
                <tr>
                    <td>
                        <h3>{{i.fid}}</h3>
                    </td>
                    <td>
                        <h3>{{i.f_name}}</h3>
                    </td>
                    <td>
                        <h3>{{i.f_desc}}</h3>
                    </td>
                    <td>
                        <h3>{{i.f_quantity}}</h3>
                    </td>
                    <td>
                        <h3>{{i.f_price}}</h3>
                    </td>
                    <td>
                        <h3>{{i.f_discount}}</h3>
                    </td>
                    <td>
                        <img src="{{i.f_img.url}}" alt="" height="100" width="150">
                    </td>
                    <td>
                        <a href="{% url 'food:food_update' pk=i.fid %}"><button>Update</button></a>
                    </td>
                    <td>
                        <a href="{% url 'food:food_delete' pk=i.fid %}"><button>Delete</button></a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        {% endblock %}
        <a href="{%url 'food:food_create' %}" class="btn btn-success w-45 py-2" type="submit">Create Food</a>
        </form>
    </main>
    {% include 'partials/_bootjs.html' %}

</body>

</html>

food/templates/item_delete.html
{% extends 'items_create.html'%}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <h2>Are You Sure To Delete</h2>
    <h3>Item No: {{res.mid}} </h3>
    <h3>Item Name: {{res.i_name}}</h3>
    <button class="btn btn-primary w-45 py-2" type="submit">Delete</button>
    <a href="{%url 'food:items_create' %}" class="btn btn-success w-45 py-2" type="submit">Items_Create</a>
</form>
{% endblock %}

food/templates/items_create.html
<!doctype html>
<html lang="en" data-bs-theme="auto">

<head>
  {% load static %}

  <script src="{% static 'js/color-modes.js' %}"></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.118.2">
  <title>Signin Template · Bootstrap v5.3</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/sign-in/">



  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

  {% include 'partials/_bootcss.html' %}

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
      z-index: 1500;
    }

    .bd-mode-toggle .dropdown-menu .active .bi {
      display: block !important;
    }
  </style>


  <!-- Custom styles for this template -->
  <link href="{% static 'css/sign-in.css'%}" rel="stylesheet">
</head>

<body class="d-flex align-items-center py-4 bg-body-tertiary">
  <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
      <path
        d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
      <path
        d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
      <path
        d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
      <path
        d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
    </symbol>
  </svg>
  <main class="form-signin w-10 m-auto">
    {% block content %}
    <form method="post">
      {% csrf_token %}
      <h1 class="h3 mb-3 fw-normal">Please Create Item</h1>
      <div>{{form}}</div>
      <br>
      <button class="btn btn-primary w-45 py-2" type="submit">Create</button>
    </form>

    <br>
    <div>
      <table border="2">
        <tr>
          <th>
            <h1>Items No</h1>
          </th>
          <th>
            <h1>Menu Items</h1>
          </th>
          <th>
            <h1>Update</h1>
          </th>
          <th>
            <h1>Delete</h1>
          </th>
        </tr>
        {% for i in res %}
        <tr>
          <td>
            <h3>{{i.mid}}</h3>
          </td>
          <td>
            <h3>{{i.i_name}}</h3>
          </td>
          <td>
            <a href="{% url 'food:item_update' pk=i.mid %}"><button>Update</button></a>
          </td>
          <td>
            <a href="{% url 'food:item_delete' pk=i.mid %}"><button>Delete</button></a>
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
    {% endblock %}
    <a href="{%url 'authe:admin_home' %}" class="btn btn-info w-45 py-2">HOME Page</a>

  </main>
  {% include 'partials/_bootjs.html' %}

</body>

</html>